services:
    web:
        build:
            context: ./
            target: dev
        volumes:
            - .:/src
        command: npm run dev
        ports: 
            - "3000:3000"
        environment:
            NODE_ENV: development
